### ISSUE TITLE
Veraltete Daten

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/community#346]
Hier eine kleine Liste an Daten die veraltet erscheinen:

andreasotte
http://www.otte.net

manuel
https://www.msc-aufenau.de.de/

nils
https://nilskoppelmann.de

tgoellner
https://thomasgoellner.de

falkomueller
https://plus.google.com/+FalkoM%C3%BCller-fotodesign

xyzettgraphix
https://plus.google.com/+xyzettgraphix

**Comment by eaCe** [comment]
@tgoellner @iceman-fx @nilskoppelmann

**Comment by iceman-fx** [comment]
Habe gestern ein Update eingestellt. Wer prüft dies denn?

**Comment by eaCe** [comment]
@iceman-fx ich habe das mal übernommen

**Comment by iceman-fx** [comment]
@eaCe hi. Muss man eigentlich noch irgendwas bei meiner Änderung machen, damit man dies in der Weltkarte sieht?
Ich sehe da nach wie vor immer noch die alten Daten.

**Comment by eaCe** [comment]
@iceman-fx hey, beim schnellen drüberfliegen sieht es für mich so aus als wären deine daten korrekt. eben wie hier im repo

**Comment by iceman-fx** [comment]
Cache ist mehrfach geleert und auf verschiedenen Systemen/Browsern getestet.

**Comment by eaCe** [comment]
Für mich sieht das korrekt aus?

![grafik](https://user-images.githubusercontent.com/2708231/189944532-9c852702-08f8-4f50-aa0c-2ea0c11833cb.png)

Deine .yml:
```yml
# teams: feel free to add multiple entries for each of your members!
name: Falko Müller

# geo location (required)
# provide your favored level of detail by number of digits (like 50.107811 vs 50.11)
# you may use services like openstreetmap.org to find out your geo location
latitude: 51.296357
longitude: 13.319603

# bio
# describe yourself, your involvement in the project and the community or whatever is relevant for you.
# should be 300 chars at maximum. no markup or line breaks!
bio: Hallo, ich bin Webentwicker/-designer und selbständiger Fotograf. REDAXO wird seit 2007 intensiv bei Kundenprojekten genutzt und mit eigenen Erweiterungen ausgebaut.

# image or gravatar
# provide image file from current folder (like 'johndoe.jpg') or gravatar url (generated via https://3v4l.org/OXG7H)
# should be square and about 200-300 px size!
image: falkomueller.jpg

# links
# one or more links to your website, your github profile, twitter, facebook et al.
# 4 links, tops!
links:
- https://www.falkomueller.com
- https://www.facebook.com/falkom360
- https://de.linkedin.com/in/fotodesign360
```
